#!/bin/bash

export PULSE_SERVER=127.0.0.1

#export XAUTHORITY                                                         
LANG=en_US.UTF-8
export LANG
echo $$ > /tmp/xsession.pid
dbus-launch 
startxfce4 &
